# . ########################## . #
#       ConsoleOnly plugin       #
#               by               #
#          SpaicyGaming          #
# . ########################## . #

Prefix:
  active: true
  prefix: '&8[&3ConsoleOnly&8]'
#
# Main Settings
Settings:
  #
  # Block commands for all players
  ConsoleOnly:
    active: true

    effects:
      # Sound played when someone execute a command listed below
      # If you want to disable this feature, just put an empty string -> ''
      sound: SLIME_ATTACK

    message: '&cThis command can only be executed by the console.'
    commands:
    - op
    - deop
    - reload
    - rl
    - ver
    - '?'
    - about
    - bukkit
    - icanasbukkit
    - plugman
    - bukkit
    - spigot
    - pl
  #
  # Block commands for the players without the permission 'consoleonly.bypass'
  BlockedCommands:
    active: true
    effects:
      sound: BAT_TAKEOFF

    message: '&cSorry, you don''t have the permission ''consoleonly.bypass''.'
    commands:
    - help
    - me
  #
  # Block all commands containing ':'
  BlocksCmdsWColons:
    active: true
    effects:
      sound: BURP

    message: '&cSorry, you can''t use the colon.'
  #
  # Block tab completition in some commands
  AntiTab:
    active: true
    commands:
    - pl
    - '?'
    - ver
    - about
  #
  # 
  WorldEditCrashFix:
    active: true
    # one '/' is added by the plugin
    commands:
    - /calc
    - /eval
    - /solve
    message: "&cI'm sorry, this server is protected :D"
    broadcast:
      active: true
      message: "&6{player} tried to crash the server"
#
# Chat Messages
Messages:
  unknownCommand: "&cUnknown command. Please, use /consoleonly help"
  noPermissions: '&cYou don''t have enough permissions to perform this command.'
  succesfullyAdded: '&cSuccessfully added command: &6&o{command}'

# . DO NOT TOUCH . #
ConfigVersion: 1.7
UpdateChecker: true