main: ${project.groupId}.${project.artifactId}.${project.name}
website: https://www.spigotmc.org/resources/consoleonly.40873/

author: SpaicyGaming
name: ${project.name}
version: ${project.name}
softdepend: [ProtocolLib]

commands:
  consoleonly:
    description: Shows subcommands.
    aliases: [co]