# . ########################## . #
#       ConsoleOnly plugin       #
#               by               #
#          SpaicyGaming          #
# . ########################## . #

Prefix: '&8[&3ConsoleOnly&8]'

#Don't put a command in both of the lists
Settings:
  ConsoleOnly:
    Active: true
    Effects:
      sounds:
        active: true
        type: SLIME_ATTACK
    Message: '&cThis command can only be executed by the console.'
    Commands:
      - op
      - deop
      - reload
      - rl
      - ver
      - '?'
      - about
      - bukkit
      - icanasbukkit
      - plugman
      - bukkit
      - spigot
      - pl
      
  BlockedCommands:    
    Active: true
    Effects:
      sounds:
        active: true
        type: BAT_TAKEOFF
    Message: '&cSorry, you don''t have the permission ''consoleonly.bypass''.'
    Commands:
      - help
      - me
      
  #BLOCKS ALL COMMANDS WITH ':'
  BlocksCmdsW/Colons:
    active: true
    Effects:
      sounds:
        active: true
        type: BURP
    message: '&cSorry, you can''t use the colon.'
  #BLOCKS AUTOCOMPLETE
  AntiTab:
    active: true
    Commands:
      - pl
      - '?'
      - ver
      - about
Messages:
  NoPermissions: '&cYou don''t have enough permissions to perform this command.'
  SuccesfullyAdded: '&cSuccesfully added command: &6&o%command%'
  
# . DO NOT TOUCH . #
ConfigVersion: 1.4
UpdateChecker: true