##################################
#       ConsoleOnly plugin       #
#               by               #
#          SpaicyGaming          #
##################################

Prefix: '&8[&3ConsoleOnly&8]'

#Don't put a command in both of the lists
Settings:
  ConsoleOnly:
    Active: true
    Effects:
      sounds:
        active: true
        type: SLIME_ATTACK
    Message: '&cThis command can only be run by the console.'
    Commands:
      - op
      - deop
      - pl
      - reload
      - rl
      - ver
      - minecraft:op
      - minecraft:deop
      - bukkit:pl
      - bukkit:ver
      
  BlockedCommands:    
    Active: true
    Effects:
      sounds:
        active: true
        type: BAT_TAKEOFF
    Message: '&cSorry, you don''t have the permission ''consoleonly.bypass''.'
    Commands:
      - help
      - minecraft:help
      - bukkit:help
      - me
      - minecraft:me
  
#Messages for /co info,reload:
Messages:
  NoPermissions: '&cYou don''t have enough permissions to perform this command.'
  WrongCommand: '&cThis command does not exist. Please use /co.'
  TooManyArgs: '&cToo many args.'

####DO NOT TOUCH###
ConfigVersion: 1.1
