main: me.spaicygaming.consoleonly.CmdsBlocker
author: SpaicyGaming
name: ConsoleOnly
version: 1.4
website: https://www.spigotmc.org/resources/consoleonly.40873/

commands:
  consoleonly:
    description: Shows subcommands.
    aliases: co