main: me.spaicygaming.consoleonly.CmdsBlocker
author: SpaicyGaming
name: ConsoleOnly
version: 1.4
website: http://bit.ly/ConsoleOnly/

commands:
  consoleonly:
    description: Shows subcommands.
    aliases: co