main: me.spaicygaming.consoleonly.CmdsBlocker
author: SpaicyGaming
name: ConsoleOnly
version: 1.1
website: http://bit.ly/ConsoleOnly

commands:
  consoleonly:
    description: Shows subcommands.
    aliases: co
