main: me.spaicygaming.consoleonly.ConsoleOnly
website: https://www.spigotmc.org/resources/consoleonly.40873/

author: SpaicyGaming
name: ConsoleOnly
version: 1.8
softdepend: [ProtocolLib]

commands:
  consoleonly:
    description: Shows subcommands.
    aliases: co